### ISSUE TITLE
util.decorateRequest mechanism may edit user provided strings

### ISSUE THREAD

**Issue by stephenplusplus** [googleapis/nodejs-common#10]
<table><th colspan=2>Copied from <a href="https://github.com/GoogleCloudPlatform/google-cloud-node/issues/1891">GoogleCloudPlatform/google-cloud-node#1891</a></th><tr><td width=70><a href="/ofrobots"><img src="https://avatars2.githubusercontent.com/u/79017?s=88&v=4" height=44 width=44></a></td><td name="20161219201517000Z">@ofrobots<br><a href="#20161219201517000Z">December 19, 2016 20:15</a></td></tr><tr><td colspan=2>

#### Environment details

  - OS: all
  - Node.js version: all
  - npm version: all 
  - google-cloud-node version: `master`

#### Steps to reproduce

The request mechanism provided used by `Service` and `ServiceObject` go through the request body and modify all occurrences of the string `{{projectId}}` and replace it with the actual project Id.

```js
const translate = require('@google-cloud/translate');
translate.detect('{{projectId}}', (err, results) => {
  console.log(results);
});
```

Output: 
```
{ language: 'fr',
  confidence: 0.15950840711593628,
  input: '{{projectId}}' }
```

It is surprising that the above example discovers **french** in the input string `{{projectId}}`! It does so happen that the actual id for my project on Google Cloud is a Quebecois phrase.

The above example is a bit contrived, but it is possible for user input to happen to contain the string `{{projectId}}`.  This is a real concern for us in the Cloud Debug agent as we capture program state upon user request and send it to the debugger API. It is quite possible for the user application to have the above string, or any other possible string, that will be silently replaced in transit. Other services like Storage, compute or resource might also have plausible failure cases.

I do like the convenience of the projectId placeholder string auto-replaced to the projectId during transit, but this leaves open the _possibility_ that valid user input may get replaced accidentally. It might be a bit less elegant/convenient, but I think we should not use a mechanism that can accidentally edit user provided strings, however unlikely.</td></tr><tr><td width=70><a href="/ofrobots"><img src="https://avatars2.githubusercontent.com/u/79017?s=88&v=4" height=44 width=44></a></td><td name="20170210223442000Z">@ofrobots<br><a href="#20170210223442000Z">February 10, 2017 22:34</a></td></tr><tr><td colspan=2>Bump. Any traction on this?</td></tr><tr><td width=70><a href="/stephenplusplus"><img src="https://avatars2.githubusercontent.com/u/723048?s=88&v=4" height=44 width=44></a></td><td name="20170216193252000Z">@stephenplusplus<br><a href="#20170216193252000Z">February 16, 2017 19:32</a></td></tr><tr><td colspan=2>The only thing I can think of is a more randomized string, e.g. `{{projectId + uuid.v1()}}`. Do you have any ideas?</td></tr><tr><td width=70><a href="/bjwatson"><img src="https://avatars2.githubusercontent.com/u/471755?s=88&v=4" height=44 width=44></a></td><td name="20170302001029000Z">@bjwatson<br><a href="#20170302001029000Z">March 2, 2017 00:10</a></td></tr><tr><td colspan=2>@stephenplusplus Could we add an optional boolean that says to interpret the string literally, rather than doing auto-replace? Kind of like the difference between `grep` and `fgrep`?</td></tr></table>

**Comment by JustinBeckwith** [comment]
Adding the approach here from an email from @ofrobots: 

- implement Service.prototype.projectIdPromise. Ideally we should remove Service.prototype.projectId as it is asynchronously initialized. (GAX based libraries will need their analogue for this. It would have been nice if there was a common-gax, but that not existing, perhaps the generator needs to be modified. I don't fully understand how the generator works)
- anything that needs a projectId to be available should do `const promise = await this.projectIdPromise` or use a promise.then. This should be easy in libraries that are already using TypeScript, but that is not a strict requirement.
- Get rid of all instances of the string {{projectId}} from across of all repos.

**Comment by sofisl** [comment]
Closing based on age, and I *think* it was addressed. Feel free to reopen if not.
