### ISSUE TITLE
Drop Promise property

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/nodejs-common#107]
From #106  by @ofrobots 

> Not a comment for this PR, but in the next semver major, can we drop support from custom Promises? Note that async/await always use native promises, so the use-case for custom promises is growing thin, and might even be footgun as things behave differently from what people might expect.
> 
> Is there a strong reason to continue supporting this? People can always do global.Promise = that.thing;

**Comment by stephenplusplus** [comment]
cc @callmehiphop -- was that just a nice thing we did, or was there a requirement or important use case?

**Comment by callmehiphop** [comment]
It was just a nice thing. Between async/await and destructuring I don't see
much of a reason to keep it around any longer.

**Comment by stephenplusplus** [comment]
Is it worth trying to figure out if we have many Bluebird users (I assume that was the most common use-case for Promise override)?

**Comment by carnesen** [comment]
There are bluebird users I'm sure. Users that rely on bluebird-specific features of the promises returned by these methods would have to do [`global.Promise = require('bluebird')`](https://github.com/petkaantonov/bluebird/issues/1026) if they weren't already.

**Comment by stephenplusplus** [comment]
Ah, gotcha. Then, since we're not blocking them, or giving them a hard time, it makes sense to remove.

**Comment by JustinBeckwith** [comment]
I just don't think this is worth addressing right now.  This would be a semver major breaking change across the board, and that's *a lot* of churn for little gain.  Unless anyone really objects, I am closing this out for now.
