### ISSUE TITLE
Allow specifying access_token to use

### ISSUE THREAD

**Issue by stephenplusplus** [googleapis/nodejs-common#11]
<table><th colspan=2>Copied from <a href="https://github.com/GoogleCloudPlatform/google-cloud-node/issues/1346">GoogleCloudPlatform/google-cloud-node#1346</a></th><tr><td width=70><a href="/salrashid123"><img src="https://avatars2.githubusercontent.com/u/11149054?s=88&v=4" height=44 width=44></a></td><td name="20160528151608000Z">@salrashid123<br><a href="#20160528151608000Z">May 28, 2016 15:16</a></td></tr><tr><td colspan=2>

There are situations where you can end up with just the access_token.  (eg. non-refereshable token for an endusers via oauth webflow).

There doesn't seem to be any way to place that raw token and initialize gcloud node. (gcloud-java recently added it in:
https://github.com/GoogleCloudPlatform/gcloud-java/issues/1029 

here are some references for the older googleapis node client:
https://github.com/google/google-api-nodejs-client#making-authenticated-requests

and a citation about overriding the config
https://github.com/GoogleCloudPlatform/gcloud-node/issues/678#issuecomment-131238194
</td></tr><tr><td width=70><a href="/mbleigh"><img src="https://avatars2.githubusercontent.com/u/1022?s=88&v=4" height=44 width=44></a></td><td name="20160624192543000Z">@mbleigh<br><a href="#20160624192543000Z">June 24, 2016 19:25</a></td></tr><tr><td colspan=2>

+1 to the issue. I've issued a [pull request](https://github.com/stephenplusplus/google-auto-auth/pull/3) against `google-auto-auth` that would allow for:

``` js
var gcloud = require('gcloud')({
  credentials: {accessToken: 'ACCESS_TOKEN_HERE'}
});
```
</td></tr><tr><td width=70><a href="/stephenplusplus"><img src="https://avatars2.githubusercontent.com/u/723048?s=88&v=4" height=44 width=44></a></td><td name="20160624194532000Z">@stephenplusplus<br><a href="#20160624194532000Z">June 24, 2016 19:45</a></td></tr><tr><td colspan=2>

Thank you for the PR over there, @mbleigh! What do you think about just not using `google-auto-auth` if a user provides a token?
</td></tr><tr><td width=70><a href="/stephenplusplus"><img src="https://avatars2.githubusercontent.com/u/723048?s=88&v=4" height=44 width=44></a></td><td name="20160819004434000Z">@stephenplusplus<br><a href="#20160819004434000Z">August 19, 2016 00:44</a></td></tr><tr><td colspan=2>

_continuing from https://github.com/GoogleCloudPlatform/gcloud-node/pull/1410#issuecomment-230762662_

There are a couple edge cases:
1. Calls made with gRPC APIs won't use the token (Datastore, Logging, Pub/Sub for now)
2. There are other libraries we use-- [gce-images](http://gitnpm.com/gce-images) & [gcs-resumable-upload](https://github.com/stephenplusplus/gcs-resumable-upload)-- that would need to be updated to accept just an access token (and we would have to provide the access token the user give us to those libraries)

@murgatroid99 is there a way to provide gRPC with just an access token?
</td></tr><tr><td width=70><a href="/murgatroid99"><img src="https://avatars2.githubusercontent.com/u/961599?s=88&v=4" height=44 width=44></a></td><td name="20160819023337000Z">@murgatroid99<br><a href="#20160819023337000Z">August 19, 2016 02:33</a></td></tr><tr><td colspan=2>

The simplest way to use a plain access token would be to add it to the call's metadata, the same way you would add it to headers for an HTTP request. If you don't want to deal with adding it to every call, you can also create a `CallCredentials` object, similarly to how you would create one for GoogleAuth credentials:

``` js
var creds = grpc.credentials.createFromMetadataGenerator(function(args, callback) {
  var metadata = new Metadata();
  metadata.add('authorization', 'Bearer: '+ access_token);
  return metadata;
});
```

Then you can pass it to a call in the options field, or compose it with SSL credentials using `grpc.credentials.combineChannelCredentials` and then using the resulting object to create a channel.
</td></tr><tr><td width=70><a href="/stephenplusplus"><img src="https://avatars2.githubusercontent.com/u/723048?s=88&v=4" height=44 width=44></a></td><td name="20160822125355000Z">@stephenplusplus<br><a href="#20160822125355000Z">August 22, 2016 12:53</a></td></tr><tr><td colspan=2>

Awesome, thanks!
</td></tr><tr><td width=70><a href="/sedouard"><img src="https://avatars2.githubusercontent.com/u/3053263?s=88&v=4" height=44 width=44></a></td><td name="20170208024943000Z">@sedouard<br><a href="#20170208024943000Z">February 8, 2017 02:49</a></td></tr><tr><td colspan=2>

Hey there. We're planning on adding GCE support to our cloud management platform. Through we're planning on getting an auth token from our users with permission scopes into GCP. Today can we pass access_token directly to this client? Or should I manually be adding the `authorization` header to all requests?</td></tr><tr><td width=70><a href="/jmuk"><img src="https://avatars2.githubusercontent.com/u/816093?s=88&v=4" height=44 width=44></a></td><td name="20170307205321000Z">@jmuk<br><a href="#20170307205321000Z">March 7, 2017 20:53</a></td></tr><tr><td colspan=2>

@stephenplusplus -- is there anything to do more?</td></tr><tr><td width=70><a href="/diiiego83"><img src="https://avatars2.githubusercontent.com/u/11553486?s=88&v=4" height=44 width=44></a></td><td name="20170714095133000Z">@diiiego83<br><a href="#20170714095133000Z">July 14, 2017 09:51</a></td></tr><tr><td colspan=2>

any update? i really need to set my access token  but i can't find a solution.</td></tr><tr><td width=70><a href="/kwent"><img src="https://avatars2.githubusercontent.com/u/879780?s=88&v=4" height=44 width=44></a></td><td name="20171019020217000Z">@kwent<br><a href="#20171019020217000Z">October 19, 2017 02:02</a></td></tr><tr><td colspan=2>

+1 for this feature</td></tr></table>

**Comment by atistler** [comment]
+1

**Comment by kwent** [comment]
@mbleigh @stephenplusplus A PR has been sitting here since June 24, 2016. How can we help to make this happen ? Looks like a lot of us need this.

**Comment by stephenplusplus** [comment]
This is unfortunately a big effort that probably requires either @callmehiphop or myself to implement, since we're familiar with the different transport layers that exist across our APIs. For example, in some places we use the REST API, and in others, gRPC directly or through an auto-generated layer called "GAPIC". Each will require a different solution, so it's not a trivial addition.

Lately, our time has been spent on supporting a wider set of APIs and their features, as well as bug fixes and performance enhancements. I can't say when we will be able to get to this, but let me ping @alexander-fenster to see if he wants to weigh in on how this should be handled and prioritized.

**Comment by kwent** [comment]
@stephenplusplus Thanks for the answer ! Please @alexander-fenster let's prioritize 🙏Thanks a lot !

**Comment by tswast** [comment]
I really like the work that @jonparrott with the [google-auth Python library](https://github.com/GoogleCloudPlatform/google-auth-library-python). I'd also love it if there was a clear way to use any kind of valid credential for our Node.js libraries.
