### ISSUE TITLE
Problems migrating to v0.18.X

### ISSUE THREAD

**Issue by nolanmar511** [googleapis/nodejs-common#123]
Right now, we're using ServiceObject.request() with a callback so we can get the error, body, and response body even when there's an error. We need to do this because the profiler API will return an error code, with a backoff specified in the body.

What can we do to migrate?

**Comment by JustinBeckwith** [comment]
Yar :(   The request method was marked as `@private`, so I broke it without prejudice: https://github.com/googleapis/nodejs-common/blob/master/src/service-object.ts#L427

The only real change here is that the method now returns a promise instead of accepting a callback.  

Calling @ofrobots @alexander-fenster @stephenplusplus - what's the deal with this method?  Is it supposed to be public?

**Comment by stephenplusplus** [comment]
Service and ServiceObject methods are meant to be private, in the sense they're not to be used directly. The request function is available to classes that extend `ServiceObject` automatically:

```js
function Storage() {}
util.inherits(Storage, common.ServiceObject)

const storage = new Storage()
storage.request()
```

**Comment by ofrobots** [comment]
I think the `@private` comment was wrong. It sounds more like a `@protected` method. I do know it is used in subclasses in quite a few places.

**Comment by nolanmar511** [comment]
I'd like to update transitive dependencies that google-cloud/profiler has through google-cloud/common.
Would it be possible to release a version 0.17 which has dependencies updated?

**Comment by ofrobots** [comment]
or, alternatively, perhaps the breaking changes to `Service#request` can be reverted.

**Comment by JustinBeckwith** [comment]
Yeah, lets do it that way.  I'll start working on a fix now.

**Comment by nolanmar511** [comment]
I'm not certain that undoing the breaking changes to `Service#request` will make it trivial to migrate.
For example, I believe `normalizeArguments` no longer supports having `null` as the first argument, which is what we currently use as the first argument. 

There seem to be some pretty notable differences between 0.17 and 0.18. I don't know how easy or difficult it will be to migrate to 0.18 even if Service#request is backwards compatible. And ultimately, there seem to be some advantages to 0.18 and there will need to be some work done to to migrate to using the types provided by 0.18.

So, it would be nice to be able to upgrade what we depend on through google-cloud/common without immediately needing to migrate to 0.18.

**Comment by JustinBeckwith** [comment]
If you can make a list here - I'm happy to work with you on the upgrade.  Hell, I can even upgrade your repo for you if you'd like.  This should be a drop in, and I need to do the work to make sure it is.
