### ISSUE TITLE
Hide extraneous GCN plumbing from returned objects

### ISSUE THREAD

**Issue by stephenplusplus** [googleapis/nodejs-common#13]
<table><th colspan=2>Copied from <a href="https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2217">GoogleCloudPlatform/google-cloud-node#2217</a></th><tr><td width=70><a href="/adam-sandor"><img src="https://avatars2.githubusercontent.com/u/10675791?s=88&v=4" height=44 width=44></a></td><td name="20170413114442000Z">@adam-sandor<br><a href="#20170413114442000Z">April 13, 2017 11:44</a></td></tr><tr><td colspan=2>

Fetching a list of files from my bucket produces 271K of JSON output from the server. And I just have 4 files in the bucket.
The data includes things like the complete description of the bucket itself (per every file) or the description of the googlecloud storage library (authors, dependencies, etc). Some of this is probably not loaded from the server but is added by the node api library. Even if that doesn't lead to network traffic it's still unnecessary and inconvenient when I try to find the relevant data. The screenshot below show the data structure with most elements collapsed. None of those elements are relevant for listing files in the bucket. I only want to see the data that is printed by `gsutil` when doing `ls`.

[https://www.dropbox.com/s/4dgpu7jh8z6lb9h/Screen%20Shot%202017-04-13%20at%2013.29.58.png?dl=0](https://www.dropbox.com/s/4dgpu7jh8z6lb9h/Screen%20Shot%202017-04-13%20at%2013.29.58.png?dl=0)

I might be missing some option or parameter that would limit the output from getFiles. 

#### Environment details

  - OS: OSX
  - Node.js version: 7.2.0
  - npm version: 3.10.9
  - google-cloud-node version: 1.0.0

#### Steps to reproduce

```
var storage = require('@google-cloud/storage');
var fs = require('fs');

var gcs = storage({
    projectId: 'MYPROJECT'
});

var bucket = gcs.bucket('MYBUCKET');

bucket.getFiles(function(err, files) {
    if (!err) {
        fs.writeFileSync("files.json", JSON.stringify(files))
    } else {
        console.error(err)
    }
});
```

</td></tr><tr><td width=70><a href="/stephenplusplus"><img src="https://avatars2.githubusercontent.com/u/723048?s=88&v=4" height=44 width=44></a></td><td name="20170413130229000Z">@stephenplusplus<br><a href="#20170413130229000Z">April 13, 2017 13:02</a></td></tr><tr><td colspan=2>

There is a lot of stuff on the object-- some is plumbing that enables our API to function. The only thing that's really meant for the user is the `metadata` property, which is the API's raw record of the resource.

In the context of `getFiles()`, the API response returns all of the metadata for each file. If we didn't include it on the object, it would require further API calls to download that information. To find the data you need, you should look into to the `metadata` object. In the case that you just want names, it's a simple map over the response:

```js
bucket.getFiles(function(err, files) {
    if (!err) {
        var fileMetadataObjects = files.map(function(file) {
            return file.metadata
        })
        fs.writeFileSync("files.json", JSON.stringify(fileMetadataObjects))
    } else {
        console.error(err)
    }
})
```

And of course, if you just want the name, you can use `file.metadata.name` or any other properties that are relevant for your use.</td></tr><tr><td width=70><a href="/stephenplusplus"><img src="https://avatars2.githubusercontent.com/u/723048?s=88&v=4" height=44 width=44></a></td><td name="20170413131247000Z">@stephenplusplus<br><a href="#20170413131247000Z">April 13, 2017 13:12</a></td></tr><tr><td colspan=2>

Just to address the 271,000 lines of JSON, though, I'm not particularly thrilled about that. From a quick test, the output of one file for me was about 1,200 lines. I'll re-open so we can define those huge objects as non-enumerable, so they're hidden from the output.</td></tr><tr><td width=70><a href="/adam-sandor"><img src="https://avatars2.githubusercontent.com/u/10675791?s=88&v=4" height=44 width=44></a></td><td name="20170414155834000Z">@adam-sandor<br><a href="#20170414155834000Z">April 14, 2017 15:58</a></td></tr><tr><td colspan=2>

Ok so do I understand correctly that only the metadata is actually downloaded from the server?</td></tr><tr><td width=70><a href="/stephenplusplus"><img src="https://avatars2.githubusercontent.com/u/723048?s=88&v=4" height=44 width=44></a></td><td name="20170414160118000Z">@stephenplusplus<br><a href="#20170414160118000Z">April 14, 2017 16:01</a></td></tr><tr><td colspan=2>

Yes, everything else is state and internal data.</td></tr><tr><td width=70><a href="/adam-sandor"><img src="https://avatars2.githubusercontent.com/u/10675791?s=88&v=4" height=44 width=44></a></td><td name="20170414162114000Z">@adam-sandor<br><a href="#20170414162114000Z">April 14, 2017 16:21</a></td></tr><tr><td colspan=2>

Cool, then it was just me panicking :) 
Still would be user friendlier to not have that metadata in the request I think.</td></tr><tr><td width=70><a href="/lukesneeringer"><img src="https://avatars2.githubusercontent.com/u/4346?s=88&v=4" height=44 width=44></a></td><td name="20170921215722000Z">@lukesneeringer<br><a href="#20170921215722000Z">September 21, 2017 21:57</a></td></tr><tr><td colspan=2>

This issue was moved to googleapis/nodejs-storage#19</td></tr><tr><td width=70><a href="/stephenplusplus"><img src="https://avatars2.githubusercontent.com/u/723048?s=88&v=4" height=44 width=44></a></td><td name="20171103145352000Z">@stephenplusplus<br><a href="#20171103145352000Z">November 3, 2017 14:53</a></td></tr><tr><td colspan=2>

This would be a change in `@google-cloud/common` that would affect all of the modules, so I'll re-open this issue here.</td></tr></table>

**Comment by stephenplusplus** [comment]
cc @irri if you would like to follow along with the progress here.

**Comment by irri** [comment]
@stephenplusplus Thanks for directing me here. Like Adam above, I feel much better knowing it does not affect network data.
