### ISSUE TITLE
Dependencies with licensing problems

### ISSUE THREAD

**Issue by jinwoo** [googleapis/nodejs-common#16]
I'm adding license checking to Google Node team's repos using our [`js-green-licenses`](https://github.com/google/js-green-licenses) tool, and finds out that nodejs-common has two problematic dependencies: log-driver & modelo.

[log-driver](https://www.npmjs.com/package/log-driver) doesn't specify any licenses. A 3-year-old [commit](https://github.com/cainus/logdriver/commit/7caec881ea7e1082c6733218398ad45650fa850b) added the ISC license and bumped its version to 1.2.6 but no NPM packages have been published with that change.

[modelo](https://www.npmjs.com/package/modelo) is in a better situation. It has the LICENSE file in its repo but its `package.json` doesn't specify its license and js-green-licenses reports that as an error.

I filed an issue for log-driver: https://github.com/cainus/logdriver/issues/9, and a PR for modelo: https://github.com/kevinconway/Modelo.js/pull/20

This issue is for tracking those problems. Once they are resolved and new npm packages are published, we have to adjust the version numbers for them accordingly.

Until then, all our packages that depend on nodejs-common must have a package whitelist for `js-green-licenses`.

**Comment by jinwoo** [comment]
kevinconway/Modelo.js#20 has been merged and a new version of npm ([v4.2.3](https://www.npmjs.com/package/modelo)) has been published.

No responses to cainus/logdriver#9 yet though.

**Comment by stephenplusplus** [comment]
log-driver@1.2.6 seems to have been published, however, jsgl isn't happy still:

```
> @google-cloud/common@0.16.0 posttest C:\Users\sawch\dev\nodejs-common
> npm run license-check


> @google-cloud/common@0.16.0 license-check C:\Users\sawch\dev\nodejs-common
> jsgl --local .

Checking package.json...

(no license): forever-agent@0.5.2
  @google-cloud/common@0.16.0 -> log-driver@1.2.6 -> codecov.io@0.0.1 -> request@2.42.0 -> forever-agent@0.5.2

(no license): combined-stream@0.0.7
  @google-cloud/common@0.16.0 -> log-driver@1.2.6 -> codecov.io@0.0.1 -> request@2.42.0 -> form-data@0.1.4 -> combined-stream@0.0.7

(no license): delayed-stream@0.0.5
  @google-cloud/common@0.16.0 -> log-driver@1.2.6 -> codecov.io@0.0.1 -> request@2.42.0 -> form-data@0.1.4 -> combined-stream@0.0.7 -> delayed-stream@0.0.5

(no license): mime@1.2.11
  @google-cloud/common@0.16.0 -> log-driver@1.2.6 -> codecov.io@0.0.1 -> request@2.42.0 -> form-data@0.1.4 -> mime@1.2.11

(no license): assert-plus@0.1.5
  @google-cloud/common@0.16.0 -> log-driver@1.2.6 -> codecov.io@0.0.1 -> request@2.42.0 -> http-signature@0.10.1 -> assert-plus@0.1.5

(no license): asn1@0.1.11
  @google-cloud/common@0.16.0 -> log-driver@1.2.6 -> codecov.io@0.0.1 -> request@2.42.0 -> http-signature@0.10.1 -> asn1@0.1.11

(no license): ctype@0.5.3
  @google-cloud/common@0.16.0 -> log-driver@1.2.6 -> codecov.io@0.0.1 -> request@2.42.0 -> http-signature@0.10.1 -> ctype@0.5.3

(no license): oauth-sign@0.4.0
  @google-cloud/common@0.16.0 -> log-driver@1.2.6 -> codecov.io@0.0.1 -> request@2.42.0 -> oauth-sign@0.4.0

(no license): aws-sign2@0.5.0
  @google-cloud/common@0.16.0 -> log-driver@1.2.6 -> codecov.io@0.0.1 -> request@2.42.0 -> aws-sign2@0.5.0

Public Domain: jsonify@0.0.0
  @google-cloud/common@0.16.0 -> log-driver@1.2.6 -> codecov.io@0.0.1 -> urlgrey@0.4.0 -> tape@2.3.0 -> jsonify@0.0.0

(no license): split@0.2.10
  @google-cloud/common@0.16.0 -> log-driver@1.2.6 -> codecov.io@0.0.1 -> urlgrey@0.4.0 -> tape@2.3.0 -> split@0.2.10

11 non-green licenses found.
```

**Comment by jinwoo** [comment]
1.2.6 seems to have pulled in more packages that have license problems. Maybe it's a good idea to abandon log-driver? Use another library or write our own?

**Comment by stephenplusplus** [comment]
@ofrobots wdyt?

**Comment by jinwoo** [comment]
All the problems come from `codecov-io@0.0.1`, which is a pretty old version. One workaround could be to fork log-driver and remove `code-cov-io` from the dependencies. It should've been in the devDependencies, I think.

**Comment by stephenplusplus** [comment]
I just noticed the same. Want to ping the maintainer who helped you with the license issue? Maybe they can make the quick fix.

**Comment by alexander-fenster** [comment]
We can as well pin version 1.2.5 for now to unblock the process - but of course would be great to resolve the license issue.

**Comment by jinwoo** [comment]
I pinged the author in https://github.com/cainus/logdriver/issues/9. But do we really need to depend on this library? It's a very thin layer on top of `console.log`.

**Comment by jinwoo** [comment]
As @ofrobots said in the chat, the latest log-driver release not only caused the license problems but more significantly security vulnerabilities: https://snyk.io/test/github/googleapis/nodejs-common?severity=high&severity=medium&severity=low

This is a big problem because lots of other google packages depend on nodejs-common and have the same vulnerabilities.

**Comment by jinwoo** [comment]
A new version of `log-driver` was published and I think it doesn't have license issues anymore.

**Comment by stephenplusplus** [comment]
Sounds right to me. We can remove the whitelist config now? (https://github.com/googleapis/nodejs-common/blob/master/js-green-licenses.json)

**Comment by jinwoo** [comment]
@stephenplusplus I believe so.

**Comment by jinwoo** [comment]
Fixed by https://github.com/googleapis/nodejs-common/pull/51

**Comment by jinwoo** [comment]
Actually this was not fixed in the npm. v0.16.1 was released *before* `log-driver` was updated to 1.2.7 by https://github.com/googleapis/nodejs-common/pull/37.

The question is why is `log-driver` pinned?

Anyway @alexander-fenster , can you please do another patch release?

**Comment by alexander-fenster** [comment]
I have just released v0.16.2. As for the `log-driver` being pinned, I guess it's a legacy from the time when I needed to pin it because of this issue :). I see no harm in it right now. Whenever the new version is released, Greenkeeper will suggest an upgrade, and if it's OK, we can unpin it then.

**Comment by jinwoo** [comment]
@JustinBeckwith What's up with all these "reopen all the closed tickets" things?

**Comment by jinwoo** [comment]
Oh, it wasn't "reopen". It was just that these things were (correctly) assigned to me retroactively. Sorry for the noise.

**Comment by JustinBeckwith** [comment]
Someone apologizing to me today for noise is rich 😆  I just spammed half the known universe.
