### ISSUE TITLE
Problems updating to 0.19.1

### ISSUE THREAD

**Issue by nolanmar511** [googleapis/nodejs-common#160]
Trying to update to the latest version, from 0.18.9, and I'm seeing this error in typescript compliation:
```
ts/src/index.ts:176:35 - error TS2551: Property 'levels' does not exist on type 'Readonly<LoggerConfig>'. Did you mean 'level'?

176     level: Logger.DEFAULT_OPTIONS.levels[config.logLevel || 2],
                                      ~~~~~~
```

Is this expected? Where are the log levels exposed now?

**Comment by JustinBeckwith** [comment]
@kjin I ran into some issues in nodejs-error-reporting as well with the logger :/  I'm not entirely familiar with the changes you made in there - would you mind taking a gander?

**Comment by nolanmar511** [comment]
I would expect [the array with the log levels](https://github.com/googleapis/nodejs-common/blob/master/src/logger.ts#L50) to be exposed somewhere.

I tried: `Logger.LEVELS[config.logLevel as number]` but still saw (about) the same error:
```
ts/src/profiler.ts:239:21 - error TS2339: Property 'LEVELS' does not exist on type 'typeof Logger'.

239       level: Logger.LEVELS[config.logLevel as number],
```

**Comment by kjin** [comment]
I actually already addressed this in #157 but I didn't think it needed to be released right away. Sorry about that, I'll open a release proposal. In the meantime, I believe lowercase `logger.LEVELS` still works.

**Comment by kjin** [comment]
@nolanmar511 v0.19.2 has been released, it should contain the fix.

**Comment by JustinBeckwith** [comment]
Thank you @kjin!
