### ISSUE TITLE
Migrate to @sindresorhus/is

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/nodejs-common#163]
We should use `@sindresorhus/is` instead of just `is`, because it's more consistent.  PR feedback from https://github.com/googleapis/nodejs-common/pull/162

**Comment by JustinBeckwith** [comment]
Blocked by https://github.com/sindresorhus/is/issues/51

**Comment by carnesen** [comment]
I've suggested a fix on sindresorhus's issue https://github.com/sindresorhus/is/issues/51#issuecomment-422925310 . We'll see what he says...

**Comment by sindresorhus** [comment]
It's out: https://github.com/sindresorhus/is/releases/tag/v0.12.0

**Comment by carnesen** [comment]
This shouldn't have "status: blocked" tag anymore ...

**Comment by zbjornson** [comment]
@JustinBeckwith would you be open to dropping the `is`-like dependency entirely? I only see six usages of it, and they appear trivial to do with vanilla JS. I'm happy to submit a PR for it.

**Comment by JustinBeckwith** [comment]
Sure!  A PR would be welcomed :)
