### ISSUE TITLE
GOOGLE_CLOUD_PROJECT env not supported?

### ISSUE THREAD

**Issue by jmdobry** [googleapis/nodejs-common#20]
I believe `GOOGLE_CLOUD_PROJECT` used to be supported, but isn't anymore?

[Here](https://github.com/googleapis/nodejs-common/blob/master/src/util.js#L591), can we change

```js
if (process.env.GCLOUD_PROJECT) {
  defaultConfig.projectId = process.env.GCLOUD_PROJECT;
}
```
to
```js
if (process.env.GCLOUD_PROJECT || process.env.GOOGLE_CLOUD_PROJECT) {
  defaultConfig.projectId = process.env.GCLOUD_PROJECT || process.env.GOOGLE_CLOUD_PROJECT;
}
```

**Comment by stephenplusplus** [comment]
I don’t think we did support it, unless it was done in auth-library. But yeah, we can support it— curious, is one more correct than the other?

**Comment by jmdobry** [comment]
Not sure, @jgeewax?

**Comment by stephenplusplus** [comment]
@jmdobry have you run into an error where it didn't recognize the project ID, or are you just going by the code? As I said above, I hadn't heard of this env name before, so we definitely didn't support it from here. However, the devs of google-auth-library knew about it: https://github.com/google/google-auth-library-nodejs/blob/7e9a3903c14340bc20ec4935138e6fb0dd8d1f8a/src/auth/googleauth.ts#L566 -- they honor both.

From our APIs, if we don't find a project ID, we set a default token for it, and replace it later with what we get from google-auth-library. So, it seems like this `GOOGLE_CLOUD_PROJECT` should still work, and the code we have to honor `GCLOUD_PROJECT` is only a minimal time saver.

**Comment by jmdobry** [comment]
The problem is that the cloud libraries are using that projectId for more than just authentication, they're using it to calculate resource paths. I believe I was doing something synchronous, (e.g. `pubsub.topic('my-topic')`), and I was trying to read the fully qualified name of the resource, but the client library hadn't gotten the projectId from the auth library, so the full resource name had just the placeholder.

**Comment by stephenplusplus** [comment]
> The problem is that the cloud libraries are using that projectId for more than just authentication, they're using it to calculate resource paths.

Do you mean the client libraries that I work on? We handle `{{projectId}}` replacement as late as possible, before an API call. We fully expect and handle the token as part of a resource.

> and I was trying to read the fully qualified name of the resource, but the client library hadn't gotten the projectId from the auth library, so the full resource name had just the placeholder.

That will always be possible, because to be sure we have a project ID, google-auth-library needs to exhaust all options of where it exists. That process is async, which is why we wait until an API request to do the replacement. The `id` or `name` property of a `common.ServiceObject` is not meant for public use.

**Comment by jmdobry** [comment]
> The `id` or `name` property of a `common.ServiceObject` is not meant for public use.

Then that requires a larger discussion. They are all documented (e.g. [Topic#name](https://cloud.google.com/nodejs/docs/reference/pubsub/latest/Topic#name), [Bucket#name](https://cloud.google.com/nodejs/docs/reference/storage/latest/Bucket#name), etc.). And given that the properties weren't named `_id` or `_name` (typically used to indicate non-public properties/methods in JavaScript) one might assume they're part of the public interface.

fwiw, `GOOGLE_CLOUD_PROJECT` is supported by a number of our Cloud Client libraries in other languages.

**Comment by stephenplusplus** [comment]
Ah, didn't know they were documented. We should remove those.

We support GOOGLE_CLOUD_PROJECT via google-auth-library. Our special casing GCLOUD_PROJECT is an artifact of the old days. It doesn’t interfere with the auth library’s process, except to sidestep it when GCLOUD_PROJECT is set.

**Comment by nolanmar511** [comment]
We'd would also like this for GoogleCloudPlatform/cloud-profiler-nodejs (google-cloud/cloud-profiler-nodejs).

**Comment by stephenplusplus** [comment]
They are both already supported, unless you found it not to work someplace?

**Comment by stephenplusplus** [comment]
Since we support `GOOGLE_CLOUD_PROJECT`, I'm going to close. If anyone finds an instance where we don't, let me know!
