### ISSUE TITLE
Typescript compilation failure when trying to upgrade to 0.21.0 from 0.20.3

### ISSUE THREAD

**Issue by nolanmar511** [googleapis/nodejs-common#204]
When trying to run typescript compilation on `@google-cloud/profiler` when upgrading  `@google-cloud/common` to 0.21.0, typescript compilation fails with:

```
ts/src/index.ts:17:9 - error TS2305: Module '"/home/node/project/node_modules/@google-cloud/common/build/src/index"' has no exported member 'Logger'.

17 import {Logger, util} from '@google-cloud/common';
```

Is the expected?

**Comment by JustinBeckwith** [comment]
Greetings!  This is entirely expected.  @ofrobots what did we do with the logging stuff in the other diagnostic modules?

**Comment by fhinkel** [comment]
Looks like it got fixed. Thanks @nolanmar511 !
