### ISSUE TITLE
Provide a way to set `highWaterMark` in streams

### ISSUE THREAD

**Issue by jimkang** [googleapis/nodejs-common#24]
#### Environment details

  - OS: All
  - Node.js version: 8.x
  - npm version: 5.x
  - @google-cloud/common version: 0.15.1

#### Steps to reproduce

  1. Try to set the `highWaterMark` on `bigquery.createQueryStream` or any other stream in the Google Cloud packages.
  2. You can't. When the limiter object is instantiated, [it passes nothing to through2](https://github.com/googleapis/nodejs-common/blob/master/src/util.js#L640). This would be its opportunity to set `highWaterMark`.

Setting `highWaterMark` allows developers to have some control over how much memory is used in memory-sensitive situations.

**Comment by jimkang** [comment]
BTW, I have been using this package about a year, and for the most part, it's been very well-behaved and readable. Thanks for working on it!

**Comment by stephenplusplus** [comment]
PR sent! #25 -- could you take a look?

**Comment by jimkang** [comment]
Thanks! I added a comment.
