### ISSUE TITLE
replaceProjectIdToken should not replace {{projectId}} in request body

### ISSUE THREAD

**Issue by kinwa91** [googleapis/nodejs-common#291]
As per discussion at https://github.com/googleapis/nodejs-storage/issues/489#issuecomment-434491153, call to `replaceProjectIdToken` when the request has a body replaces the body that contains `{{projectId}}`.

It's unlikely user's request would contain the `{{projectId}}` placeholder, but it should probably be fixed.

**Comment by stephenplusplus** [comment]
I think #10 covers the concerns here, but please re-open if you think we need to take more immediate steps to patch a hole somewhere.
