### ISSUE TITLE
Service.request no longer returns a promise? (regression 0.27 -> 0.28)

### ISSUE THREAD

**Issue by vieira** [googleapis/nodejs-common#354]
#### Environment details

  - OS: macOS 10.14.3
  - Node.js version: v10.15.0
  - yarn version: 1.13.0
  - `@google-cloud/common` version:  0.28

#### Steps to reproduce

After updating from `@google-cloud/common": "0.27.0"` to `0.28`, the method `request` from `Service` no longer seems to return a promise, instead returning `undefined`. I noticed that if I pass a callback I get the expected response/error, but before I was able to `await` or invoke `then/catch` on the resulting promise, which is of course much more convenient.

```js
babel.config.js  node_modules/    services/
vieira@giant ~/C/platform> vim index.js

const x = this.(...).request({
  method: 'PUT',
  uri: `subscriptions/${this.name}`,
  body: {
    topic: `projects/${projectId}/topics/${topic}`,
    ackDeadlineSeconds: this.ackDeadlineSeconds,
  },
  json: true, 
});

// x used to be a Promise and now is undefined
```

Thanks!

**Comment by JustinBeckwith** [comment]
Greetings!  This was a change we had to make to ensure backwards compat with previous versions of the library.  Sadly, this isn't something we're likely to change due to the large amount of modules that relied on that *not* existing.  You should be able to wrap this with `util.promisify` to get the same effect though.  

Out of curiosity - what are you using this library for?  I wouldn't have imagined many folks were using it independent of the other cloud libs :)

**Comment by vieira** [comment]
Hello @JustinBeckwith,

While I understand that, the change to ensure backwards compat with previous versions of the library broke backwards compat with previous versions of the library (with 0.27 and multiple others) and I can't see any advantages of having a callback based API instead of a Promise based one. 

I understand that you have multiple stakeholders inside Google and their requests have a higher priority than the rest of the community, however this is a public package published by Google, one should at least be able to upgrade between minor versions without (too much) fear.

I am using this library because there is no Google provided library for the REST interface of Google Cloud Pub/Sub and I cannot use grpc because it depends on a binary.
