### ISSUE TITLE
Fix visibility annotations for Service.prototype.request

### ISSUE THREAD

**Issue by ofrobots** [googleapis/nodejs-common#359]
`Service.prototype.request` has a jsdoc annotation marking it private. It has no local uses, so private cannot be the intent. I am pretty sure that the intention was for it to be protected.

Can we 
1. Figure out the right visibility for this function.
1. Make it a proper typescript visibility modifier rather than jsdoc comment.

**Comment by callmehiphop** [comment]
I don't think we want to make it protected, or private for that matter. Some APIs only have partial implementations for whatever reason (*coughcomputeccough*) and in the past we've mentioned if a particular endpoint is not covered the user can still call it by calling `.request()` directly.

**Comment by ofrobots** [comment]
If it public, the jsdoc shouldn't call it private. @JustinBeckwith shouted me the other day about using a private API.
