### ISSUE TITLE
Release v2.1.0 is not backward compatible

### ISSUE THREAD

**Issue by jqll** [googleapis/nodejs-common#463]
#### Environment details

  - OS: Linux
  - `@google-cloud/common` version: v2.1.0

While compiling https://github.com/googleapis/cloud-profiler-nodejs, we see the error message:
Tue Aug  6 00:07:36 UTC 2019: ts/src/profiler.ts:444:9 - error TS2345: Argument of type '{ method: string; uri: string; body: { deployment: Deployment; profileType: string[]; }; json: boolean; timeout: number; }' is not assignable to parameter of type 'DecorateRequestOptions'.
Tue Aug  6 00:07:36 UTC 2019: Types of property 'method' are incompatible.
Tue Aug  6 00:07:36 UTC 2019: Type 'string' is not assignable to type '"GET" | "HEAD" | "POST" | "PUT" | "OPTIONS" | undefined'.

I believe https://github.com/googleapis/nodejs-common/pull/448 changed the interface for DecorateRequestOptions.method. Release v2.1.0 probably shouldn't be a minor release, as the change is not backward compatible.

**Comment by JustinBeckwith** [comment]
This *should* be resolved, as we rolled back the `dist` tag on `@google-cloud/common` to a compatible version 👍

**Comment by nolanmar511** [comment]
v2.1.1 is also not backward compatible for typescript compilation.

We see the same errors again with the latest release.
