### ISSUE TITLE
Update dependency teeny-request to ^5.3.1

### ISSUE THREAD

**Issue by maxiruani** [googleapis/nodejs-common#498]
Currently, the version of teeny-request is ^5.2.1
Since then, there have been some [bug fixes](https://github.com/googleapis/teeny-request/blob/master/CHANGELOG.md#531-2019-10-29) in that dependency.

I would like to take advantage of those fixes on ^5.3.1 version.

Thanks!

**Comment by bcoe** [comment]
@maxiruani `^5.2.1` should pull in `5.3.1`, based on the semver rule, I recommend potentially regenerating your `package-lock.json`.

I'll leave this open and we will make sure to explicitly update the dependency soon however.

**Comment by maxiruani** [comment]
@bcoe You were right, sorry for this issue. I reinstalled everything, but the `package-lock.json` was fixed to the old version.
Thanks for answering so quickly!
