### ISSUE TITLE
Switch to renovate from greenkeeper?

### ISSUE THREAD

**Issue by stephenplusplus** [googleapis/nodejs-common#59]
[Renovate](https://renovateapp.com), originally introduced to me by @JustinBeckwith, seems to do what Greenkeeper does, but with *a lot* more control.

Issues with Greenkeeper so far:

- Opens issues about failing builds before they've even completed
  - This leaves lots of stale branches from the erroneous issues (just deleted 23 in one repo)
- Will not update package-lock.json file when it updates a dependency (but there is [this tool](https://github.com/greenkeeperio/greenkeeper-lockfile) that can do it)

Cool renovate features:

- [All of these choices for configuration](https://renovateapp.com/docs/config-presets/config-default)
- Scheduling -- you can have it run whenever, all at once, so we're not chasing PRs at all hours of the day
- It can [automerge](https://renovateapp.com/docs/deep-dives/noise-reduction#automerging) its own PRs after our tests pass
- It will update package-lock.json in a PR
- It can update packages & package-lock.json on a weekly basis
- It can rebase its own PRs automatically when the base branch is updated (e.g. when we merge another PR)

Things it does not do:

- Open issues if a new version in our covered release range fails.
  - Is this a concern, since we have nightly builds now?

I like the idea of switching to any tool that can promise us less headaches, and do more work for us, instead of us chasing it around and cleaning up after it. I think renovate can help us focus on real work :)

cc @alexander-fenster @callmehiphop @ofrobots

**Comment by JustinBeckwith** [comment]
Sounds like a win to me.

**Comment by ofrobots** [comment]
> It can automerge its own PRs after our tests pass

This actually wouldn't be allowed as per the Google org. policy – cannot grant `master` branch write permissions to a third-party bot, unless special requirements are met.

The other features look a win to me though. I'd be open to trying it. Does it require org. admin rights to enable for a given repo?

**Comment by alexander-fenster** [comment]
One other bonus is that they claim it supports monorepos, so samples' `package.json` will be updated as well (greenkeeper always ignores it, and it's a problem, even though we haven't face any serious consequences with it yet).

I'm ready to try it, with one problem: googleapis repos are controlled by @lukesneeringer, not by me :) Luke, do you feel you'll have some time this week to experiment with replacing greenkeeper with Renovate for several repos? (I would start with common and maybe some small fully codegen repo such as cloud-container or os-login)

**Comment by lukesneeringer** [comment]
Yes, I am very willing to try this, and can do it this week.

**Comment by alexander-fenster** [comment]
If so, I would say the sequence should be:

1. disable GreenKeeper for all `googleapis/nodejs-.*` projects, I remember reading that they don't support such moves and it would require talking to their support, so it's easier to just disable preventively;
1. move to GoogleCloudPlatform;
1. enable Renovate for the first few repos to see how it works;
1. enable Renovate OR GreenKeeper for all repos based on the results of the evaluation.

Does this plan look good to you?

**Comment by stephenplusplus** [comment]
Just for notekeeping: https://github.com/googleapis/github-repo-automation has been switched to renovate. Configuration file: https://github.com/googleapis/github-repo-automation/blob/master/renovate.json

**Comment by JustinBeckwith** [comment]
@stephenplusplus @jonparrott I don't have admin on this repo, so I can't set it up :(  Would someone with admin mind doing it?  I'd really rather use renovate if we can.

**Comment by alexander-fenster** [comment]
We can not (yet) because Renovate cannot work with our weird samples stuff (the `npm link` is required to run lint). Still thinking of possible solutions (but not much has been done during the last month, I need to get back to this). Discussion [here](https://github.com/dialogflow/dialogflow-nodejs-client-v2/pull/41) and one possible solution [here](https://github.com/dialogflow/dialogflow-nodejs-client-v2/pull/50) but need to get @jmdobry's feedback.

**Comment by JustinBeckwith** [comment]
This is done 🤗
