### ISSUE TITLE
Transient network errors not retried (FetchError: network timeout)

### ISSUE THREAD

**Issue by vieira** [googleapis/nodejs-common#610]
Although nodejs-common should implement a retry mechanism using retry-request, it seems some network errors are not being retried (or not respecting the `maxRetries` option), e.g.:

```
Failed to pull messages from <subscription> FetchError: network timeout at: https://pubsub.googleapis.com/v1/projects/<project-id>/subscriptions/<subscription>:pull
at Timeout.<anonymous> (/app/index.js:54566)
at listOnTimeout (internal/timers.js:549)
at processTimers (internal/timers.js:492)
```

#### Environment details

  - OS: Linux (cos) on GKE; macOS 10.14.6
  - Node.js version: v10.22.0
  - yarn version: 1.22.4
  - `@google-cloud/common` version: 3.3.2

#### Steps to reproduce

Steps to reproduce

1. Make a request while network connection is down.
2. Notice that it immediately fails without any retry being made.

Thanks!

Note: This might be related to #473 although the kind of error that is not being retried this time seems to be different.

**Comment by stephenplusplus** [comment]
Hello! I've tried to reproduce this, but could not see the immediate failure. From the looks of the error, you're making the request through the Pub/Sub library? It would be good to see the actual code you're using, as we may need to look elsewhere.

To help test this library directly, I wrote some system tests (PR: #612) that check both types of retries we perform (through retry-request): pre-flight (e.g. no network) and response (e.g. 501). It seems to confirm we are attempting to retry requests correctly. (I did catch one bug, but it's not related to pre-flight errors)

**Comment by vieira** [comment]
Hello, I am using `nodejs-common` directly to implement a library to interact with Pub/Sub via HTTP/REST (instead of grpc which is used by the official Pub/Sub library).

The error occurs here:

```js
const { receivedMessages = [] } = await this.client.request({
  body: { returnImmediately, maxMessages },
  method: 'POST',
  uri: `subscriptions/${this.name}:pull`,
  json: true,
}).catch((err) => {
  console.error(`Failed to pull messages from ${this.name}`, err);
  return {};
});
```

the constuctor looks like this:

```js
class PubSub extends Service {
  constructor(options) {
    const config = {
      baseUrl: `https://pubsub.googleapis.com/v1/projects/${options.projectId}`,
      projectIdRequired: false,
      scopes: [
        'https://www.googleapis.com/auth/iam',
        'https://www.googleapis.com/auth/cloud-platform',
        'https://www.googleapis.com/auth/pubsub',
      ],
      packageJson,
    };
    super(config, options);
  }
```

and is called with:

```js
const client = new PubSub({
  projectId: GOOGLE_PROJECT_ID,
  credentials: {
    client_email: GOOGLE_CLIENT_EMAIL,
    private_key: GOOGLE_PRIVATE_KEY,
  },
  maxRetries: 10, 
});
```

**Comment by vieira** [comment]
As a workaround I changed the first block of code, which seems to "resolve" the issue. However I would prefer the library handled this kind of transient errors with more care than I do here. 😜 

```js
const { receivedMessages = [] } = await retry(async (bail) => {
  try {
    return await this.topic.client.request({
      body: { returnImmediately, maxMessages },
      method: 'POST',
      uri: `subscriptions/${this.name}:pull`,
      json: true,
    }); 
  } catch (err) {
    // XXX: Temporary workaround to retry on network errors, see issue:
    // https://github.com/googleapis/nodejs-common/issues/610
    if (err.name !== 'FetchError') { 
      bail(err);
      return {}; 
    }   
    throw err;
  }
}).catch((err) => {
  console.error(`Failed to pull messages from ${this.name}`, err);
  return {}; 
});
```

**Comment by stephenplusplus** [comment]
Thanks for the code. I'm still not able to figure it out! This code passes both offline and online:

```js
const assert = require('assert');
const common = require('@google-cloud/common');

const MOCK_HOST_PORT = 8118;
const MOCK_HOST = `http://localhost:${MOCK_HOST_PORT}`;

const service = new common.Service({
  baseUrl: MOCK_HOST,
  apiEndpoint: MOCK_HOST,
  scopes: [],
  packageJson: {name: 'tests', version: '1.0.0'},
});

// This mocks what retry-request does to calculate the retry delay
function getMinimumRetryDelay(retryNumber: number) {
  return Math.pow(2, retryNumber) * 1000;
}

let minExpectedResponseTime = 0; // (this turns out to be 6000)
let numExpectedRetries = 2;

while (numExpectedRetries--) {
  minExpectedResponseTime += getMinimumRetryDelay(numExpectedRetries + 1);
}

const timeRequest = Date.now();

service.request(
  {
    uri: '/mock-endpoint-no-response',
  },
  err => {
    const timeResponse = Date.now();
    assert(err.message.includes('ECONNREFUSED') === true);
    assert(timeResponse - timeRequest > minExpectedResponseTime);
  }
);
```

Is there anything you see there that I can change to reproduce the error?

**Comment by vieira** [comment]
I will try to gather more information, right now I can only add that the error object contains the attribute `type: 'request-timeout'` in addition to the message I posted.

Do you think it is possible that it is indeed retrying but not respecting the `maxRetries` option that is passed to Service constructor?

**Comment by stephenplusplus** [comment]
Hey @vieira, it looks like I was not only wrong, but found a bug along the way. So, a belated sorry, but thank you! are in order.

First, I missed how you were passing `maxRetries`. It should actually be in the `config`, as opposed to the `options` passed to the Service constructor:

```diff
class PubSub extends Service {
  constructor(options) {
    const config = {
      baseUrl: `https://pubsub.googleapis.com/v1/projects/${options.projectId}`,
      projectIdRequired: false,
      scopes: [
        'https://www.googleapis.com/auth/iam',
        'https://www.googleapis.com/auth/cloud-platform',
        'https://www.googleapis.com/auth/pubsub',
      ],
      packageJson,
+     maxRetries: options.maxRetries,
    };
    super(config, options);
  }
```

Also, this is actually a different type of retry, which has its own control:

```diff
class PubSub extends Service {
  constructor(options) {
    const config = {
      baseUrl: `https://pubsub.googleapis.com/v1/projects/${options.projectId}`,
      projectIdRequired: false,
      scopes: [
        'https://www.googleapis.com/auth/iam',
        'https://www.googleapis.com/auth/cloud-platform',
        'https://www.googleapis.com/auth/pubsub',
      ],
      packageJson,
      maxRetries: options.maxRetries,
+     noResponseRetries: options.noResponseRetries,
    };
    super(config, options);
  }
```

Although, I wouldn't use that yet, as it will endlessly loop (that bug I mentioned). A PR is coming to correct that.
