### ISSUE TITLE
Looking for error handling documentation

### ISSUE THREAD

**Issue by jgehrcke** [googleapis/nodejs-common#618]
Hello! When trying to built a rather robust system using client libraries based on googleapis/nodejs-common then of course it's important to know how these libraries handle errors internally, how they expose errors to the application developer, and how the application developer is then recommended to deal with those errors that the libraries expose.

Specifically, I am missing documentation that describes

- which errors I can expect by API calls to be thrown, and how to catch them (and only them :-))
- to which degree transient errors (on TCP level, but also on layer 7) are handled internally by the library (e.g., via retrying), and how I can influence that behavior as an application developer.

One detail question, when developing in TypeScript, for example is: can I rely on the `ApiError`, and in particular on `err instanceof ApiError` within an error handler?

Maybe I just didn't find the right document yet?

I want to say that while I could (and will) of course simply try things out an important insight from various years of developing against robust client libraries in other ecosystems is: **well-documented error handling specifics** give me the warm feeling that I am developing against a well-specified interface, as opposed to developing against ever-changing implementation details.

Also, error handling is hard to get right and it's always good to see how the library authors would do it!

Thanks for help!

**Comment by fhinkel** [comment]
Greetings, we're closing this. Looks like the issue got resolved. Please let us know if the issue needs to be reopened.
