### ISSUE TITLE
replace teeny-request with a fetch api?

### ISSUE THREAD

**Issue by jimmywarting** [googleapis/nodejs-common#710]
Given that [request](https://www.npmjs.com/package/request) have been deprecated for a long time now... how do you feel about replacing the teeny-request with using node-fetch directly instead? 

teeny-request is only a thin layer around node-fetch anyway.

**Comment by danielbankhead** [comment]
This library is mostly in maintenance mode. Replacing the `teeny-request` library is a bit risky for this library at the moment.
