### ISSUE TITLE
Use es6 classes and exports in logger.ts

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/nodejs-common#80]
Logger.ts currently uses the `export = Logger` style syntax.  Lets move towards explicit exported classes or functions and es module syntax.

**Comment by kjin** [comment]
@JustinBeckwith Should we turn `Logger` into a class? It seems to depend on `log-driver` right now but maybe we can use this opportunity to change that?

**Comment by JustinBeckwith** [comment]
I'm not sure if it should be a class or just exported functions 🤷‍♂️ as long as it's using es modules, I'm happy.  On the log-driver dependency - I'm all for chopping out dependencies we don't need, but I am trying to avoid breaking changes to the library right now.  So far I think we've kept it compatible, and at the moment I'd like to preserve the API.  If we can do that while chopping the dependency, and not adding too much code, I'm all for it.
